# Given: A DNA string s of length at most 1000 nt.
# Return: Four integers (separated by spaces) counting the respective number of times that the symbols 'A', 'C', 'G', and 'T' occur in s.

# Sample Dataset: AGCTTTTCATTCTGACTGCAACGGGCAATATGTCTCTGTGTGGATTAAAAAAAGAGTGTCTGATAGCAGC
# Sample Output: 20 12 17 21

SAMPLE_DATASET = 'TTGTAGTCCCTAAGTCGGCGCTGATCAGAACAGTACATCATTGTCCCATTTACTCATACCGTAGCCATCTCAGGAATCACAGTACTATACACGATAATATTTTTATCGCCCTACCAGGAGATTTTAAACAACCTCAGGTACCTTCCCTTAACTCAAGGAGGTGAGATCCTGCCTCCGTATTGCACCGGAAGATCACGCCAGGAGCTGCACTCCTCAATGAATCACGTCCATCTGAATGCGACTCGGTGTTGAGCCTAATTGCCTAGCTCCTGGGAACGGTCGATAGAACTGGGCATGGCCTCGTATTTAAGAGGTAGTTGCCACAGGCAAAGACACAGGCGTCTCGTCTGCCACCTTACTATCTCCCTTGGTTATAATCTGGACGAAGGATTGCGCTCTAGCTACCTAGAATCATTTAACTTAGTCTTTGCACTGCGACGCCGTTCTTAGGGTACATGCGCAGTCCACATTAGTTCGAGTGTGGACATAATCCTGTCGCTGGAAACGTCTACTGCGAATCTAGGGGCTTCGGGGATATCAGTTTGACACTAGGGACGCCGTAATAAGGTATTCATAAGGCAATGACCTCCGATTAAGCGTAGTGCATCCAAACCGTTAGAAGCTACGACGGTAACCCGGAGAGGACTCCACGCCTACCCCCTCTGCAAACTGAATAGAACTACCTGTAGCTTTATTAGTCGAGCCACCAATTGTTGAGTTTGTATAAATATATGCCTAGAGGTCGACATCGGCGATGTTAGGGGCTGACCTCAGCCCGCTGAGTGTCAACTAAAAAGAAAGAGCCATAGATGACATACGCTTCAA'


def count_letters(dna_string):
    output = { 'A': 0, 'C': 0, 'G': 0, 'T': 0 }

    for letter in dna_string:
        output[letter] += 1

    return output

output = count_letters(SAMPLE_DATASET)

print 'A: ', output['A']
print 'C: ', output['C']
print 'G: ', output['G']
print 'T: ', output['T']
